name: unit-tests
on: [push, workflow_dispatch]
jobs:
  unit-tests:
    runs-on: debian-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version: 3.x
      - run: flutter pub get
      - run: flutter test